spring:
  profiles:
    active: release
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lifecycle
    username: admin
    password: life12!
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate #??? ?? ??. ?? validate??
      show-sql : true
      format_sql : true
      naming: #?? ??? ??????? Repositoy?? ????? ????? ?? DB???? ?????? ???? ???? ??? ??? ???????? ?? ??? ???? ??? ?? ??? ????? ?.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  logging:
    level:
      org:
        springframework:
          web: WARN
        hibernate:
          dialect: TRACE